<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BotTelegram" nsURI="http://org.eclipse.example.BotTelegram"
    nsPrefix="org.eclipse.example.BotTelegram">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="App">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Users" upperBound="-1"
        eType="#//Usuario" containment="true" eOpposite="#//Usuario/Aplicacion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NombreUnico"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NombreUnico" value="self.Aplicacion -> isUnique(Nombre)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cedula" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Telefono" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Aplicacion" lowerBound="1"
        eType="#//App" eOpposite="#//App/Users"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Packages" upperBound="-1"
        eType="#//Paquete" containment="true" eOpposite="#//Paquete/User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paquete">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NombreUnicoIdPack"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NombreUnicoIdPack" value="self.Flight -> isUnique(IdPack)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IdPack" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ida" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vuelta" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Aerolinea" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumAsientos" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Precio" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Flight" upperBound="-1"
        eType="#//Vuelo" containment="true" eOpposite="#//Vuelo/Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="User" lowerBound="1" eType="#//Usuario"
        eOpposite="#//Usuario/Packages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factura" lowerBound="1"
        eType="#//Factura" containment="true" eOpposite="#//Factura/Packs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vuelo">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Origen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Destino" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DuracionMin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FechaIda" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FechaVuelta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Package" lowerBound="1"
        eType="#//Paquete" eOpposite="#//Paquete/Flight"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factura">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrecioBase" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ValorFinal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Packs" eType="#//Paquete"
        eOpposite="#//Paquete/factura"/>
  </eClassifiers>
</ecore:EPackage>
